### Q.1 무작위 데이터를 가진 5x3의 행렬을 가지는 numpy array와 3x2 행렬을 가지는 numpy array를 만든 후 행렬곱 연산을 진행

In [1]:
import numpy as np

arr1 = np.random.rand(5, 3)
arr2 = np.random.rand(3, 2)

dot = arr1 @ arr2

In [2]:
print(dot, dot.shape)

[[1.0188159  1.054193  ]
 [1.15064076 1.38147583]
 [0.57392096 0.80194314]
 [0.5570627  0.7357424 ]
 [1.10926218 1.15101475]] (5, 2)


### Q2. 두 numpy array의 concatenate 연산을 구하시오.

In [3]:
import numpy as np

arr1 = np.array([[5, 7], [9, 11]], float)
arr2 = np.array([[2, 4], [6, 8]], float)

concat_1 = np.concatenate((arr1, arr2), axis=0)
concat_2 = np.concatenate((arr1, arr2), axis=1)

print(concat_1)
print(concat_2)

[[ 5.  7.]
 [ 9. 11.]
 [ 2.  4.]
 [ 6.  8.]]
[[ 5.  7.  2.  4.]
 [ 9. 11.  6.  8.]]


### Q3. 주어진 데이터를 경사하강법을 위해 데이터를 분리 하시오.

In [4]:
import numpy as np

xy = np.array([[1., 2., 3., 4., 5., 6.],
              [10., 20., 30., 40., 50., 60.]])

x_train = xy[0]
y_train = xy[1]

print(x_train, x_train.shape)
print(y_train, y_train.shape)

[1. 2. 3. 4. 5. 6.] (6,)
[10. 20. 30. 40. 50. 60.] (6,)


### Q4. 경사 하강법 구현을 위해서 분리한 x_train 데이터와 계산될 weight, bias 값을 정의해보세요.

In [5]:
import numpy as np

beta_gd = np.random.rand(1)
bias = np.random.rand(1)

print(beta_gd, bias)

[0.33461002] [0.2382222]


### Q5. linear regression을 경사하강법 구현을 위한 학습 Loop 으로 구현 하시오.
#### (최종적으로 1000회 반복했을 시에 결과를 출력)

In [6]:
import numpy as np

xy = np.array([[1., 2., 3., 4., 5., 6.],
              [3., 6., 9., 12., 15., 18.]])

x_train = xy[0]
y_train = xy[1]

beta_gd = np.random.rand(1)
bias = np.random.rand(1)

learning_rate = 0.01

for i in range(1000):
    pred = (x_train * beta_gd) + bias
    error = ((pred - y_train) ** 2).mean()

    gd_w = ((pred - y_train) * 2 * x_train).mean()
    gd_b = ((pred - y_train) * 2).mean()

    beta_gd -= learning_rate * gd_w
    bias -= learning_rate * gd_b

    if i % 100 == 0:
        print('Epoch ({:10d}/1000) error: {:10f}, beta_gd: {:10f}, bias:{:10f}'.format(i, error, beta_gd.item(), bias.item()))

Epoch (         0/1000) error: 122.896784, beta_gd:   0.867597, bias:  0.846405
Epoch (       100/1000) error:   0.151653, beta_gd:   2.793396, bias:  0.884512
Epoch (       200/1000) error:   0.072994, beta_gd:   2.856664, bias:  0.613650
Epoch (       300/1000) error:   0.035133, beta_gd:   2.900557, bias:  0.425733
Epoch (       400/1000) error:   0.016910, beta_gd:   2.931009, bias:  0.295362
Epoch (       500/1000) error:   0.008139, beta_gd:   2.952136, bias:  0.204914
Epoch (       600/1000) error:   0.003918, beta_gd:   2.966793, bias:  0.142164
Epoch (       700/1000) error:   0.001886, beta_gd:   2.976962, bias:  0.098629
Epoch (       800/1000) error:   0.000908, beta_gd:   2.984017, bias:  0.068426
Epoch (       900/1000) error:   0.000437, beta_gd:   2.988911, bias:  0.047472
